name: Music

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build with Gradle
        # Maine yahan '--no-build-cache' add kiya hai taaki logo aur buffering ka purana data ekdam saaf ho jaye
        run: ./gradlew clean :composeApp:assembleDebug --stacktrace --no-build-cache

      - name: Find and Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Abhi-Music-3
          path: "**/build/outputs/apk/**/*.apk"
